version: '3.8'

services:
  faq-generator:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./static/screenshots:/app/static/screenshots
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
